export interface Idea {
  id: string
  title: string
  content: string
  keywords: string[]
  sourceUrl?: string
  bookmarked?: boolean
  createdAt: string
}

export const mockIdeas: Idea[] = [
  {
    id: '1',
    title: 'AI 기반 개인화 추천 시스템',
    content: '머신러닝을 활용하여 사용자의 행동 패턴을 분석하고 개인화된 콘텐츠를 추천하는 시스템을 개발하고 싶다. 협업 필터링과 콘텐츠 기반 필터링을 결합하여 정확도를 높일 수 있을 것 같다.',
    keywords: ['AI', '머신러닝', '추천시스템', '개인화', '협업필터링'],
    sourceUrl: 'https://example.com/ai-recommendation',
    bookmarked: true,
    createdAt: '2024-01-15T10:30:00.000Z',
  },
  {
    id: '2',
    title: '블록체인을 활용한 디지털 신원 인증',
    content: '분산 원장 기술을 사용하여 개인의 신원 정보를 안전하게 관리하고 검증할 수 있는 시스템. 중앙 집중식 데이터베이스의 취약점을 해결하고 사용자가 자신의 데이터를 직접 제어할 수 있게 한다.',
    keywords: ['블록체인', '신원인증', '보안', '분산시스템', '디지털신원'],
    sourceUrl: 'https://example.com/blockchain-identity',
    bookmarked: true,
    createdAt: '2024-01-18T14:20:00.000Z',
  },
  {
    id: '3',
    title: '실시간 협업 에디터 개발',
    content: '여러 사용자가 동시에 문서를 편집할 수 있는 실시간 협업 에디터. Operational Transform나 CRDT 알고리즘을 사용하여 충돌 없이 동시 편집을 지원한다. Google Docs나 Notion과 유사한 기능을 구현하고 싶다.',
    keywords: ['협업', '실시간', '에디터', 'CRDT', 'OperationalTransform'],
    sourceUrl: 'https://example.com/collaborative-editor',
    bookmarked: false,
    createdAt: '2024-01-20T09:15:00.000Z',
  },
  {
    id: '4',
    title: 'IoT 센서 데이터 시각화 대시보드',
    content: '다양한 IoT 센서에서 수집된 데이터를 실시간으로 모니터링하고 시각화하는 대시보드. 온도, 습도, 조도, 움직임 감지 등 여러 센서 데이터를 통합하여 관리할 수 있다. React와 D3.js를 활용하여 인터랙티브한 차트를 구현한다.',
    keywords: ['IoT', '센서', '데이터시각화', '대시보드', '실시간모니터링'],
    sourceUrl: 'https://example.com/iot-dashboard',
    bookmarked: true,
    createdAt: '2024-01-22T16:45:00.000Z',
  },
  {
    id: '5',
    title: '음성 인식 기반 스마트 홈 제어',
    content: '자연어 처리와 음성 인식을 결합하여 음성 명령으로 집안의 전자기기를 제어하는 시스템. "불 켜줘", "온도 올려줘" 같은 자연스러운 명령을 이해하고 실행한다.',
    keywords: ['음성인식', 'NLP', '스마트홈', 'IoT', '자연어처리'],
    sourceUrl: 'https://example.com/voice-control',
    bookmarked: false,
    createdAt: '2024-01-25T11:30:00.000Z',
  },
  {
    id: '6',
    title: '그래프 데이터베이스를 활용한 소셜 네트워크 분석',
    content: 'Neo4j나 ArangoDB 같은 그래프 데이터베이스를 사용하여 소셜 네트워크의 관계를 모델링하고 분석한다. 영향력 있는 사용자, 커뮤니티 탐지, 정보 전파 경로 등을 분석할 수 있다.',
    keywords: ['그래프데이터베이스', '소셜네트워크', 'Neo4j', '네트워크분석', '커뮤니티탐지'],
    sourceUrl: 'https://example.com/graph-database',
    bookmarked: true,
    createdAt: '2024-01-28T13:20:00.000Z',
  },
  {
    id: '7',
    title: '마이크로서비스 아키텍처 설계 패턴',
    content: '대규모 애플리케이션을 작은 독립적인 서비스로 분해하는 마이크로서비스 아키텍처. API Gateway, Service Mesh, Circuit Breaker 패턴 등을 활용하여 안정성과 확장성을 확보한다.',
    keywords: ['마이크로서비스', '아키텍처', 'API Gateway', 'Service Mesh', '분산시스템'],
    sourceUrl: 'https://example.com/microservices',
    bookmarked: false,
    createdAt: '2024-02-01T10:00:00.000Z',
  },
  {
    id: '8',
    title: '컴퓨터 비전을 활용한 의료 이미지 분석',
    content: '딥러닝 모델을 사용하여 X-ray, CT 스캔, MRI 이미지를 분석하고 질병을 조기 진단하는 시스템. CNN과 Transfer Learning을 활용하여 의료진의 진단을 보조한다.',
    keywords: ['컴퓨터비전', '딥러닝', '의료AI', '이미지분석', 'CNN'],
    sourceUrl: 'https://example.com/medical-ai',
    bookmarked: true,
    createdAt: '2024-02-03T15:30:00.000Z',
  },
  {
    id: '9',
    title: '서버리스 함수를 활용한 이벤트 처리 파이프라인',
    content: 'AWS Lambda나 Google Cloud Functions를 사용하여 이벤트 기반 아키텍처를 구현한다. 비동기 작업 처리, 웹훅 처리, 데이터 변환 등의 작업을 서버리스 함수로 처리하여 비용을 최적화한다.',
    keywords: ['서버리스', 'Lambda', '이벤트처리', '비동기', '클라우드'],
    sourceUrl: 'https://example.com/serverless',
    bookmarked: false,
    createdAt: '2024-02-05T09:45:00.000Z',
  },
  {
    id: '10',
    title: '증강현실(AR) 기반 쇼핑 경험',
    content: 'AR 기술을 활용하여 사용자가 가상으로 제품을 체험할 수 있는 쇼핑 앱. 가구 배치, 옷 입어보기, 메이크업 시도 등을 AR로 구현하여 구매 결정을 돕는다.',
    keywords: ['AR', '증강현실', '쇼핑', '가상체험', '모바일앱'],
    sourceUrl: 'https://example.com/ar-shopping',
    bookmarked: true,
    createdAt: '2024-02-08T12:15:00.000Z',
  },
  {
    id: '11',
    title: '자동화된 테스트 프레임워크 구축',
    content: 'CI/CD 파이프라인에 통합할 수 있는 자동화된 테스트 프레임워크. 단위 테스트, 통합 테스트, E2E 테스트를 자동으로 실행하고 코드 커버리지를 측정한다. Jest, Cypress, Playwright 등을 활용한다.',
    keywords: ['테스트', '자동화', 'CI/CD', '코드커버리지', 'E2E'],
    sourceUrl: 'https://example.com/testing-framework',
    bookmarked: false,
    createdAt: '2024-02-10T14:00:00.000Z',
  },
  {
    id: '12',
    title: '엣지 컴퓨팅을 활용한 실시간 데이터 처리',
    content: '클라우드 대신 엣지 디바이스에서 데이터를 처리하여 지연 시간을 최소화한다. IoT 센서 데이터를 엣지에서 필터링하고 집계하여 네트워크 트래픽을 줄이고 실시간성을 확보한다.',
    keywords: ['엣지컴퓨팅', '실시간', 'IoT', '데이터처리', '지연시간최소화'],
    sourceUrl: 'https://example.com/edge-computing',
    bookmarked: true,
    createdAt: '2024-02-12T16:30:00.000Z',
  },
  {
    id: '13',
    title: '자연어 생성 모델을 활용한 콘텐츠 작성 도구',
    content: 'GPT나 BART 같은 언어 모델을 활용하여 블로그 포스트, 마케팅 문구, 이메일 초안 등을 자동으로 생성하는 도구. 사용자의 톤과 스타일에 맞춰 조정할 수 있다.',
    keywords: ['NLP', '자연어생성', 'GPT', '콘텐츠작성', '언어모델'],
    sourceUrl: 'https://example.com/nlg-tool',
    bookmarked: false,
    createdAt: '2024-02-15T10:20:00.000Z',
  },
  {
    id: '14',
    title: '분산 추적 시스템 구현',
    content: '마이크로서비스 환경에서 요청의 흐름을 추적하는 분산 추적 시스템. OpenTelemetry나 Jaeger를 사용하여 각 서비스 간의 호출을 모니터링하고 성능 병목을 찾는다.',
    keywords: ['분산추적', '마이크로서비스', 'OpenTelemetry', '모니터링', '성능분석'],
    sourceUrl: 'https://example.com/distributed-tracing',
    bookmarked: true,
    createdAt: '2024-02-18T13:45:00.000Z',
  },
  {
    id: '15',
    title: '웹소켓을 활용한 실시간 채팅 시스템',
    content: 'WebSocket을 사용하여 다중 사용자 간 실시간 채팅을 구현한다. Redis Pub/Sub을 활용하여 여러 서버 인스턴스 간 메시지를 동기화하고, 읽음 표시, 타이핑 인디케이터 등의 기능을 추가한다.',
    keywords: ['WebSocket', '실시간', '채팅', 'Redis', 'Pub/Sub'],
    sourceUrl: 'https://example.com/realtime-chat',
    bookmarked: false,
    createdAt: '2024-02-20T11:00:00.000Z',
  },
  {
    id: '16',
    title: '강화학습을 활용한 게임 AI',
    content: 'Deep Q-Network(DQN)나 Proximal Policy Optimization(PPO) 같은 강화학습 알고리즘을 사용하여 게임 AI를 학습시킨다. 플레이어의 행동 패턴을 학습하고 적응형 난이도를 제공한다.',
    keywords: ['강화학습', '게임AI', 'DQN', '머신러닝', '적응형난이도'],
    sourceUrl: 'https://example.com/rl-game-ai',
    bookmarked: true,
    createdAt: '2024-02-22T15:15:00.000Z',
  },
  {
    id: '17',
    title: 'GraphQL API 설계 및 최적화',
    content: 'REST API 대신 GraphQL을 사용하여 클라이언트가 필요한 데이터만 요청할 수 있게 한다. DataLoader를 사용하여 N+1 쿼리 문제를 해결하고, 스키마 스티칭으로 여러 데이터 소스를 통합한다.',
    keywords: ['GraphQL', 'API', 'DataLoader', '스키마스티칭', '최적화'],
    sourceUrl: 'https://example.com/graphql-api',
    bookmarked: false,
    createdAt: '2024-02-25T09:30:00.000Z',
  },
  {
    id: '18',
    title: '쿠버네티스 클러스터 자동 스케일링',
    content: 'Horizontal Pod Autoscaler(HPA)와 Cluster Autoscaler를 설정하여 트래픽에 따라 자동으로 파드와 노드를 스케일링한다. 메트릭 기반 스케일링 정책을 수립하여 비용을 최적화한다.',
    keywords: ['쿠버네티스', '자동스케일링', 'HPA', '클라우드', 'DevOps'],
    sourceUrl: 'https://example.com/k8s-autoscaling',
    bookmarked: true,
    createdAt: '2024-02-28T14:00:00.000Z',
  },
  {
    id: '19',
    title: '차세대 웹 표준: WebAssembly 활용',
    content: 'WebAssembly를 사용하여 C/C++/Rust로 작성된 고성능 코드를 브라우저에서 실행한다. 이미지 처리, 암호화, 게임 엔진 등 성능이 중요한 작업에 활용한다.',
    keywords: ['WebAssembly', '성능최적화', 'Rust', '브라우저', '웹표준'],
    sourceUrl: 'https://example.com/webassembly',
    bookmarked: false,
    createdAt: '2024-03-02T10:45:00.000Z',
  },
  {
    id: '20',
    title: '데이터 레이크 아키텍처 설계',
    content: '대용량 데이터를 저장하고 분석하기 위한 데이터 레이크를 구축한다. AWS S3나 Azure Data Lake Storage를 사용하여 다양한 형식의 데이터를 저장하고, Apache Spark로 대규모 데이터 처리를 수행한다.',
    keywords: ['데이터레이크', '빅데이터', 'Apache Spark', '데이터분석', '클라우드스토리지'],
    sourceUrl: 'https://example.com/data-lake',
    bookmarked: true,
    createdAt: '2024-03-05T16:20:00.000Z',
  },
]


